### ISSUE TITLE
Clear the open npm advisories and review the override set

### ISSUE THREAD

**Issue by jefrykurniaone** [jefrykurniaone/porto-jefry#56]
## Parent

Spec: #51 — clear the open npm advisories and review the override set

## What to build

An audit that reads zero, and an override set that is true.

Start by re-measuring. Four high-severity advisories were open before this run began — a denial of service in the brace-expansion package (whose pinned version is itself inside the affected range), the glob matcher that consumes it, quadratic CPU consumption in the YAML parser ESLint loads configuration through, and an unbounded loop in the identifier generator PostCSS depends on. The upgrade ticket in this run has since refreshed every in-range dependency, so some of those may already be gone and something else may have appeared. Read the advisory list from the lockfile, not from the installed tree, and work from what it actually says.

For each advisory, take the least-binding remedy that clears it: first, let a refreshed parent resolve a patched version on its own; failing that, raise the project's own declared range; and only then add or raise an override. An override is a standing liability — two of the four advisories are against versions the project's own overrides pinned — so the bias is towards removing overrides, not adding them.

Then review the override set as a whole, including entries no advisory touches. Every survivor gets a written reason. Any that no longer serves one goes.

Two constraints are load-bearing and must survive intact. ESLint stays on 9 — a plugin the project depends on peer-caps there and calls an API the next major removed, so moving ESLint is not an available route to a clean audit. And the glob-matcher pin is only safe while no enabled lint rule calls that package in its old callable style; three installed plugins still do, inside rules the configuration does not turn on. Run lint after the pins move, specifically to prove that is still true — the failure it produces is loud and names the package.

Finally, make the repository's guidance about the overrides match the manifest. It currently claims the overrides hold the audit at zero, which has not been true for some time.

No application source, styling, or configuration outside the dependency manifest, the lockfile, and that guidance may change.

## Acceptance criteria

- [ ] The advisory list read from the lockfile is quoted in the completion report both before and after the change.
- [ ] The audit, measured from the lockfile, reports zero advisories at every severity.
- [ ] No override in the manifest names a version covered by an open advisory.
- [ ] Every surviving override carries a written reason; overrides that no longer serve one are removed, and the report says which and why.
- [ ] ESLint still resolves to a 9.x version.
- [ ] Lint passes, with no "not a function" failure from the glob-matcher consumers.
- [ ] Typecheck passes and a production build succeeds.
- [ ] The built CSS still contains both spellings of the vendor-prefixed backdrop-filter declaration — the build path moved, so this is re-checked.
- [ ] The repository guidance describing the overrides matches what the manifest now contains.
- [ ] No application source file is modified.

## Execution

- **Model**: Opus. **Effort**: high — judgment is most of the work: which remedy each advisory gets, which overrides survive, and keeping two coupled pins compatible without silently changing which lint rules run.

## Blocked by

- The Next.js 16.3.4 upgrade ticket — it rewrites the same lockfile, and its refresh changes which advisories are still open.
- The production verification ticket — the production measurement for the CV fix is taken before another dependency change reaches the live site.

**Comment by jefrykurniaone** [comment]
## Completion record — ticket #56 (wave 4 of map #57)

Landed. The audit reads zero, and it got there by removing three overrides and adding none.

**Delivery**

| | |
|---|---|
| Branch | `chore/clear-npm-advisories` (deleted, both sides) |
| Commit | `606063a` — `chore: drop brace-expansion, minimatch, sharp overrides, npm audit now zero` |
| Pull request | #62, merged as merge commit `df9d996` |
| Executor | Opus, effort `high`, per the ticket's labels |
| Hand-backs | None |

### The advisory list, before and after, read from the lockfile

Before, on `main` at `a0c05d2` — 2 high. Both were the pair the wave 1 upgrade left behind, and both were against versions this repository's own overrides pinned:

```
brace-expansion  4.0.0 - 5.0.8
Severity: high
brace-expansion: DoS via unbounded intermediate arrays, bypassing the CVE-2026-14257 mitigation - https://github.com/advisories/GHSA-rgw5-rvv9-x895
node_modules/brace-expansion
  minimatch  10.0.0 || 10.0.2
  Depends on vulnerable versions of brace-expansion
  node_modules/minimatch

2 high severity vulnerabilities
```

After, on the branch and again on merged `main`:

```
found 0 vulnerabilities
```

Both readings were taken by the orchestrator independently of the executor, with `npm audit --package-lock-only` — from the lockfile, not from the installed tree — and matched what the executor reported.

### The remedy each advisory took

**`brace-expansion` (GHSA-rgw5-rvv9-x895).** The override was removed, with nothing put in its place. The pinned `5.0.8` sat inside the advisory's own affected range (`>=4.0.0 <5.0.9`), so the override *was* the advisory. `brace-expansion@5.0.9` is published, and `minimatch@10.2.6` declares `brace-expansion: ^5.0.8`, so the patched version resolves on its own with no range raise and no pin. Nothing is less binding than deleting an override.

Raising the pin to `^5.0.9` instead would have been worse than merely heavier: it would have forced `brace-expansion@5` onto the `minimatch@3` branches and reproduced `expand is not a function`.

**`minimatch` (flagged through `brace-expansion`).** Removed with it. It was never an independent finding — the override existed only to keep `minimatch` on a major that consumes `brace-expansion@5`, and that constraint disappeared with the pin above.

### The override set, reviewed as a whole

Removed:

| Override | Why it no longer serves a purpose |
|---|---|
| `brace-expansion: "5.0.8"` | Pinned a version inside the open advisory's range. Unpinned, `minimatch@10.2.6` — required by `eslint-plugin-sonarjs` and `@typescript-eslint/typescript-estree` — resolves the patched `5.0.9` by itself. |
| `minimatch: "^10.2.5"` | Existed only to feed `brace-expansion@5`. With that pin gone, the `minimatch@3.1.5` copies take `brace-expansion@1.1.18`, which no advisory covers. |
| `sharp: "$sharp"` | A measured no-op after the wave 1 upgrade. `next@16.3.4` declares `sharp: ^0.35.4` as an optional dependency and the root declares `^0.35.4`; both resolve `0.35.4`, deduped, with or without the override. Verified by removing it and re-resolving — the tree is identical, and the lockfile carries exactly one `sharp`. |

Kept, each verified by removal-and-re-resolve rather than by assumption:

| Override | Measured reason |
|---|---|
| `postcss: "$postcss"` | `next@16.3.4` depends on `postcss` at the exact version `8.5.23`; the root range `^8.5.15` resolves `8.5.26`. Remove the override and the tree carries both copies. |
| `@emnapi/core: "1.11.0"`, `@emnapi/runtime: "1.11.0"`, `@emnapi/wasi-threads: "1.2.2"` | The WebAssembly fallback runtime, reached through four different ranges by `@tailwindcss/oxide-wasm32-wasi`, `@unrs/resolver-binding-wasm32-wasi`, `@img/sharp-wasm32` and `@napi-rs/wasm-runtime`. Without the pins the tree resolves three copies of `@emnapi/core`, four of `@emnapi/runtime` and two of `@emnapi/wasi-threads`. Dedupe only; no advisory is involved. |

**The `sharp` 0.35.0 floor is untouched and still enforced**, now by the root dependency range `^0.35.4` and by `next@16.3.4`'s own optional declaration rather than by an override. Nothing in the resolved tree can reach below 0.35.0.

### The minimatch hazard is retired rather than dormant

`eslint-plugin-import@2.32.0`, `eslint-plugin-react@7.37.5` and `eslint-plugin-jsx-a11y@6.10.2` now all resolve `minimatch@3.1.5` — the callable version they are written against. Under the old override they received v10, and enabling `import/order`, `react/no-danger` or `jsx-a11y/label-has-associated-control` would have crashed lint with `minimatch is not a function`. That failure mode no longer exists. Confirmed from the merged lockfile by the orchestrator:

```
3.1.5   node_modules/eslint-plugin-import/node_modules/minimatch
3.1.5   node_modules/eslint-plugin-react/node_modules/minimatch
3.1.5   node_modules/eslint-plugin-jsx-a11y/node_modules/minimatch
1.1.18  (their brace-expansion, in each case)
10.2.6  node_modules/minimatch
5.0.9   node_modules/brace-expansion
9.39.5  node_modules/eslint
0.35.4  node_modules/sharp
8.5.26  node_modules/postcss
```

No lint configuration changed, so the enabled rule set is identical before and after.

### The manifest diff

```diff
-        "postcss": "$postcss",
-        "sharp": "$sharp",
-        "brace-expansion": "5.0.8",
-        "minimatch": "^10.2.5"
+        "postcss": "$postcss"
```

Three files in total: `package.json`, `package-lock.json`, and `CLAUDE.md`. **No application source file was modified.** The `src/utils/constants.ts` churn that `npm run prebuild` produces during a build was reverted, in the worktree and again in the main checkout after the post-merge gate.

### Completion gate — run whole on the branch by the executor, and again on merged `main` by the orchestrator

| Command | Branch | Merged `main` |
|---|---|---|
| `npm run lint` | pass | pass, exit 0 |
| `npx tsc --noEmit` | pass | pass, exit 0 |
| `npm run build` | pass | pass, exit 0 |
| `npm audit --package-lock-only` | `found 0 vulnerabilities` | `found 0 vulnerabilities` |

CI on #62 (`Lint, Typecheck, Build`) passed independently in 39 seconds, and the Vercel preview deployment succeeded.

The vendor-prefix check passes on merged `main`, prefixed form first, which is what the repository's styling note requires:

```
.site-nav{z-index:100;-webkit-backdrop-filter:blur(16px);backdrop-filter:blur(16px);background:var(--bg);position:fixed;top:0;left:0;right:0}
```

The route table is unchanged in shape: `ƒ /[locale]`, `ƒ /[locale]/[...rest]`, `ƒ /api/generate-cv`, `○ /_not-found`, `○ /sitemap.xml`, `ƒ Proxy (Middleware)`.

### Runtime verification on production

`postcss` and `sharp` both sit on paths this change touched, so the CV endpoint was re-exercised on the production deployment of `df9d996` (`dpl_BxAZCg1JjA4aVBd593oVgrJ2nVwi`, `READY`, production), as a visitor would:

| Locale | Status | Content-Type | Content-Disposition | Bytes | Vercel cache |
|---|---|---|---|---|---|
| `en` | 200 | `application/pdf` | `attachment; filename="Jefry_Kurniawan_CV_EN.pdf"` | 128,056 | MISS |
| `id` | 200 | `application/pdf` | `attachment; filename="Jefry_Kurniawan_CV_ID.pdf"` | 127,609 | MISS |

Both `MISS`, so each request executed the function rather than being served from an edge cache. Structural inspection of both files: header `%PDF-1.3`, trailer `%%EOF`, exactly one `/Subtype /Image` XObject filtered `DCTDecode` at 400 × 400 with a JPEG SOI marker present — the profile photo, which only exists if `sharp` loaded and ran. Byte counts are identical to those measured in #55 before this change. The project's runtime error table reports no runtime errors of any kind in the window since the deployment.

### Acceptance criteria

- [x] The advisory list read from the lockfile is quoted both before and after the change.
- [x] The audit, measured from the lockfile, reports zero advisories at every severity.
- [x] No override in the manifest names a version covered by an open advisory.
- [x] Every surviving override carries a written reason; three were removed and the report says which and why.
- [x] ESLint still resolves to 9.39.5.
- [x] Lint passes, with no `minimatch is not a function` failure.
- [x] Typecheck passes and a production build succeeds.
- [x] Both spellings of the vendor-prefixed backdrop-filter declaration survive in the built CSS.
- [x] The repository guidance describing the overrides matches the manifest.
- [x] No application source file is modified.

### One deviation from the spec's expectation, recorded deliberately

Spec #51's Further Notes predicted the `sharp: "$sharp"` override would survive this review, because vercel/next.js#96064 — the framework bundling a vulnerable `sharp` — is still open. It did not survive, and the reason is that the wave 1 upgrade changed the fact the prediction rested on: `next@16.3.4` now declares `sharp: ^0.35.4` itself, so the framework no longer pins an older copy for the override to hoist. The override was verified to be a no-op by removing it and re-resolving, and the merged lockfile carries exactly one `sharp` at `0.35.4`. Production confirms it independently — the CV endpoint loads the module and embeds the photo. If a future Next.js release reintroduces an older nested `sharp`, the override is the remedy to reinstate, and the guidance now says so.

### Noted, not acted on

`npm install` warns that install scripts are not approved for `@parcel/watcher@2.6.0`, `@swc/core@1.16.1` and `unrs-resolver@1.12.2` (`npm warn allow-scripts`). Pre-existing, unrelated to any advisory, and `npm approve-scripts` changes install behaviour — outside this ticket's scope, and worth its own decision.

---

### Wave 4 closed

| Ticket | Executor | Review request | Merge commit | Hand-backs |
|---|---|---|---|---|
| #56 | Opus / `high` | #62 | `df9d996` | none |

Wave 4 held this ticket alone by design: it returns to the manifest, the lockfile and the guidance file, all of which the earlier waves had finished with.

Orchestrator housekeeping done: `main` fast-forwarded to `df9d996`; the branch deleted on both sides; the worktree removed by the junction-safe procedure. That mattered again here — the Turbopack build left two junctions under `.next/node_modules/` (`sharp-20c6a5da84e2135f` and `@react-pdf/renderer-5f716e9bc7d68b8a`). Both pointed inside the worktree's own dependency tree rather than into the main checkout, because this ticket was given its own full install instead of a shared junction; they were unlinked before removal regardless, and the main checkout's `sharp`, `@react-pdf/renderer` and `next` were confirmed intact afterwards. The main checkout was then reinstalled from the new lockfile.

This was the map's final wave. Map #57 and both specs close next.
