### ISSUE TITLE
Upgrade Next.js to 16.3.4 and refresh in-range dependencies

### ISSUE THREAD

**Issue by jefrykurniaone** [jefrykurniaone/porto-jefry#52]
## Parent

Spec: #50 — restore production CV PDF download (Next.js 16.3.4)

## What to build

The project runs Next.js 16.3.4, which contains the Turbopack file-tracing fix that makes the CV endpoint's native image dependency load in a deployed function. `eslint-config-next` moves with it, every other dependency moves to its latest in-range version, and the lockfile is regenerated in one change. Nothing about the application's behaviour is meant to change; this ticket is the version move plus the evidence that it did not break anything a static check can see.

Two things must be true of the resolved graph afterwards, because they are why the endpoint broke in the first place: `sharp` resolves at or above 0.35.4 (the framework's own optional dependency now asks for that, and every version below 0.35.0 carries the libvips advisories), and only one copy of `sharp` is installed. Downgrading `sharp` is not an available remedy for anything encountered here.

The advisory position is a comparison, not an absolute: four high-severity advisories are already open on the default branch before this work starts, and clearing them belongs to a different spec. Record the advisory set read from the lockfile before touching anything, and compare against it afterwards. Introducing a new advisory fails this ticket; leaving the existing four alone does not.

If the upgrade surfaces breakage, fix it inside this ticket rather than working around it — but report anything that changes observable behaviour rather than absorbing it silently. The 16.3 release deprecates several TypeScript compiler options the project does not use, and ships a codemod for a cache feature the project does not use; neither is expected to apply.

## Acceptance criteria

- [ ] `next` and `eslint-config-next` both resolve to 16.3.4 in the lockfile, and the declared ranges in the manifest permit exactly that.
- [ ] Every other dependency has moved to its latest version within its already-declared range; no declared range was widened to achieve it.
- [ ] `sharp` resolves at 0.35.4 or above, and exactly one copy of it exists in the resolved tree.
- [ ] ESLint remains on 9.x — the pin is deliberate and load-bearing.
- [ ] Lint passes.
- [ ] Typecheck passes.
- [ ] A production build succeeds.
- [ ] The built CSS contains both the prefixed and the unprefixed spelling of the backdrop-filter declaration. Check the build output, never the source.
- [ ] The advisory set read from the lockfile after the change is a subset of the set recorded before it. Both lists are quoted in the completion report.
- [ ] No application source file is modified except where the upgrade genuinely required it; any such change is called out explicitly in the completion report with its reason.

## Execution

- **Model**: Opus. **Effort**: high — the target is one version bump, but the executor decides how to handle whatever the refresh surfaces, and every later ticket in the run builds on the lockfile this one produces.

## Blocked by

- None — can start immediately.

**Comment by jefrykurniaone** [comment]
## Completion record — ticket #52 (wave 1 of map #57)

Landed. Next.js is on 16.3.4 on `main`, and the in-range dependency refresh went in as one change alongside it.

**Delivery**

| | |
|---|---|
| Branch | `fix/next-16-3-4-dep-refresh` (deleted, both sides) |
| Commit | `a846034` — `fix: bump next to 16.3.4 so sharp libvips reach function bundle` |
| Pull request | #59, merged as merge commit `f06e6ea` |
| Executor | Opus, effort `high`, per the ticket's labels |
| Hand-backs | None |

**Resolved versions, read from the lockfile**

| Package | Version |
|---|---|
| `next` | 16.3.4 |
| `eslint-config-next` | 16.3.4 |
| `eslint` | 9.39.5 — the 9.x pin held |
| `sharp` | 0.35.4 |

`sharp` exists as exactly one copy: `node_modules/sharp` at 0.35.4, with the copy under `next` deduped onto it. No nested second install.

Other packages that moved within their already-declared ranges: `postcss` 8.5.26, `next-intl` 4.14.1, `typescript` 5.9.3, `js-yaml` 4.3.2, `nanoid` 3.3.18, `minimatch` 10.2.6. After the refresh, `npm outdated` reports `Current` equal to `Wanted` for every package — the in-range moves are exhausted. The only rows it lists at all are `eslint` (latest 10.9.1), `@types/node` (26.4.0) and `typescript` (7.0.2), all outside their declared ranges and all deliberately not taken.

**Advisory comparison, read from the lockfile with `npm audit --package-lock-only`, not from the installed tree**

Before, on `main` at `857bf44` — 4 high:

- `brace-expansion` 4.0.0 – 5.0.8 — GHSA-rgw5-rvv9-x895
- `js-yaml` 4.0.0 – 4.3.0 — GHSA-5p4m-2wfm-xmqj
- `minimatch` 10.0.0 || 10.0.2 — vulnerable via `brace-expansion`
- `nanoid` <3.3.18 — GHSA-2v37-7h3g-55p8

After, on the branch — 2 high:

- `brace-expansion` 4.0.0 – 5.0.8 — GHSA-rgw5-rvv9-x895
- `minimatch` 10.0.0 || 10.0.2 — vulnerable via `brace-expansion`

A strict subset, and nothing new. `js-yaml` and `nanoid` cleared as a side effect of the refresh, because their patched versions already sat inside ranges the tree declared. The two that remain are the override-pinned pair, which is ticket #56's work in wave 4. Both lists were re-measured independently by the orchestrator against `main` and against the branch, and matched.

**Manifest changes — three lines, all narrowings, none widened**

- `next`: `^16.2.12` → `^16.3.4`
- `eslint-config-next`: `^16.2.12` → `^16.3.4`
- `sharp`: `^0.35.3` → `^0.35.4`

The old ranges already permitted the new versions, so none of these was required to resolve 16.3.4. They were narrowed for two stated reasons: `next@16.3.4` declares `sharp: ^0.35.4` as an optional dependency and the `sharp: "$sharp"` override feeds the root range string down to the nested copy, so leaving `^0.35.3` invited an override/dependency conflict; and pinning the framework floor stops a later `npm update` from silently taking 16.4.x. This is stricter than the acceptance criterion asked for, not looser.

**No application source file was modified.** The diff is `package.json` (3 lines) and `package-lock.json` only. `src/utils/constants.ts` was rewritten by `npm run prebuild` during the build, changing `LAST_MODIFIED_DATE` from `'2026-08-11'` to `'2026-09-01'`; that date churn was the only diff in the file, so it was reverted and not committed. The `overrides` block was not touched.

**Completion gate — run whole on the branch by the executor, and again on merged `main` by the orchestrator**

| Command | Branch | Merged `main` |
|---|---|---|
| `npm run lint` | pass | pass, exit 0 |
| `npx tsc --noEmit` | pass | pass, exit 0 |
| `npm run build` | pass | pass, exit 0 |

CI on #59 (`Lint, Typecheck, Build`) passed independently in 46s, and the Vercel preview deployment succeeded.

The build-output check for the vendor-prefixed declaration passes in both places, prefixed form first, which is what the repository's styling note requires:

```
-webkit-backdrop-filter:blur(16px);backdrop-filter:blur(16px);
```

The `-webkit-mask-image` / `mask-image` pair on `.hero__grid-overlay` also survived Lightning CSS.

The route table is unchanged in shape after the upgrade: `ƒ /[locale]`, `ƒ /[locale]/[...rest]`, `ƒ /api/generate-cv`, `○ /_not-found`, `○ /sitemap.xml`, `ƒ Proxy (Middleware)`. The locale route is still rendered per request, which the theming and CSP notes require.

**Nothing surfaced that changed observable behaviour.** The 16.3 TypeScript compiler-option deprecations and the cache-components codemod both concern features this project does not use, and neither applied. Lint did not hit `minimatch is not a function`, so no enabled rule calls the matcher in the callable v3 style — the coupled `brace-expansion` / `minimatch` overrides are still safe as documented.

**Left for later tickets, deliberately:** the two remaining advisories and the override review (#56); everything that needs a real deployment — the CV endpoint per locale, the CSP nonce on the served HTML, locale routing and the language toggle, the theme cookie on first render (#53 against the preview, #55 against production).

---

### Wave 1 closed

| Ticket | Executor | Review request | Merge commit | Hand-backs |
|---|---|---|---|---|
| #52 | Opus / `high` | #59 | `f06e6ea` | none |

Wave 1 held this ticket alone by design — it owns the manifest and the lockfile for the whole run, and every later ticket reads from what it landed.

Orchestrator housekeeping done: `main` fast-forwarded to `f06e6ea`; the branch deleted on both sides; the worktree removed by the junction-safe procedure. That last one mattered here — the Turbopack build left two junctions under `.next/node_modules/` (`sharp-<hash>` and `@react-pdf/renderer-<hash>`). Both pointed inside the worktree's own dependency tree rather than into the main checkout, because this ticket was given its own full install instead of a shared junction, so nothing outside the worktree was at risk; they were unlinked before removal regardless, and the main tree's `sharp` and `@react-pdf/renderer` were confirmed intact afterwards. The main checkout's dependencies were then reinstalled from the new lockfile.

Next frontier is wave 2: #53 (orchestrator-run, against the preview deployment) and #54 (documentation), with no file contention between them. The preview deployment this ticket produced is preserved at `https://porto-jefry-erbthfvho-jefry-kurniawan-s-projects.vercel.app` (commit `a846034`), so #53 still has its target even though the branch is gone.
